function(clapack_read_make_objects output_variable makefile_path source_directory)
    set(source_groups ${ARGN})
    file(STRINGS "${makefile_path}" makefile_lines)
    set(all_sources)

    foreach(source_group IN LISTS source_groups)
        set(found_group FALSE)
        set(reading_group FALSE)
        set(group_value "")

        foreach(makefile_line IN LISTS makefile_lines)
            if(NOT reading_group)
                if(NOT makefile_line MATCHES "^[ \t]*${source_group}[ \t]*=[ \t]*(.*)$")
                    continue()
                endif()
                set(line_fragment "${CMAKE_MATCH_1}")
                set(found_group TRUE)
                set(reading_group TRUE)
            else()
                set(line_fragment "${makefile_line}")
            endif()

            string(REGEX REPLACE "[ \t]*#.*$" "" line_fragment "${line_fragment}")
            if(line_fragment MATCHES "\\\\[ \t]*$")
                string(REGEX REPLACE "\\\\[ \t]*$" "" line_fragment "${line_fragment}")
                string(APPEND group_value " ${line_fragment}")
            else()
                string(APPEND group_value " ${line_fragment}")
                break()
            endif()
        endforeach()

        if(NOT found_group)
            message(FATAL_ERROR "Source group ${source_group} was not found in ${makefile_path}")
        endif()

        string(REGEX REPLACE "[ \t]+" ";" group_objects "${group_value}")
        foreach(group_object IN LISTS group_objects)
            if(group_object STREQUAL "")
                continue()
            endif()
            if(NOT group_object MATCHES "\\.o$")
                message(FATAL_ERROR
                    "Unexpected token '${group_object}' in ${source_group} from ${makefile_path}")
            endif()

            string(REGEX REPLACE "\\.o$" ".c" source_file "${group_object}")
            get_filename_component(source_path
                "${source_directory}/${source_file}" ABSOLUTE)
            if(NOT EXISTS "${source_path}")
                message(FATAL_ERROR "Source file does not exist: ${source_path}")
            endif()
            list(APPEND all_sources "${source_path}")
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES all_sources)
    set(${output_variable} "${all_sources}" PARENT_SCOPE)
endfunction()